name: Build & Publish Release

on:
  workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '10.0.x'
    - name: Build Ur
      run: dotnet build Ur.sln --configuration Release
    - name: Test
      run: dotnet test Ur.sln
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1
    - name: Publish Ur to NuGet
      run: nuget.exe push Ur\bin\MonoGame\Release\Ur.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
