name: Build & Publish Beta

on:
    push:
        paths:
            - '.github/**'
            - 'Ur/**'
            - 'Ur.Tests/**'
    workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '10.0.x'
    - name: Build Ur
      run: dotnet build Ur.slnx --configuration Release
    - name: Test
      run: dotnet test Ur.slnx